### ISSUE TITLE
[Bug]: Unable to auth or re-auth with Evernote account

### ISSUE THREAD

**Issue by ach1000** [vzhd1701/evernote-backup#103]
### evernote-backup version

Tested with 1.9.2 and 1.9.3

### What OS are you using?

Linux

### OS Version / Linux distribution

Debian (12 / Bookworm)

### Bug description

My nightly crontab to backup my Evernote notes failed with:

```
Reading database en_backup.db...
Authorizing auth token, evernote backend...
Authentication token expired or revoked!
```

Trying to init-db ore-auth I get:

```
Traceback (most recent call last):
  File "evernote_backup/cli.py", line 305, in main
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1688, in invoke
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "evernote_backup/cli.py", line 291, in reauth
  File "evernote_backup/cli_app.py", line 80, in reauth
  File "evernote_backup/cli_app_auth.py", line 56, in get_auth_token
  File "evernote_backup/cli_app_auth_password.py", line 56, in evernote_login_password
  File "evernote_backup/evernote_client_auth.py", line 27, in login
  File "evernote_backup/evernote_client.py", line 138, in wrapper
  File "evernote_backup/evernote_client_util.py", line 28, in wrapper
  File "evernote_backup/evernote_client_classes.py", line 294, in authenticateLongSessionV2
  File "evernote/edam/userstore/UserStore.py", line 781, in recv_authenticateLongSession
evernote.edam.error.ttypes.EDAMSystemException: EDAMSystemException(message=None, errorCode=8, rateLimitDuration=None)
```

My account is protected with 2FA, but the exception occurs after entering username/password; we don't get as far as requesting the 2FA token.

Can re-produce with the latest binary release.

**Comment by FabThelead** [comment]
i have the same issue.

**Comment by Houska1** [comment]
I'm not the developer, but I've proposed an edit to the README documentation to clarify the situation as a stopgap. See https://github.com/vzhd1701/evernote-backup/pull/109.  Due to Evernote policies, OAuth is now essentially required and should probably becomes default behaviour, with username and pwd passed from command line or solicited by evernote-backup and sent to Evernote servers an optional alternate (for backend China, for instance).

**Comment by huyz** [comment]
Try `evernote-backup reauth --oauth`

**Comment by vzhd1701** [comment]
Fixed in the new version. OAuth will be used by default now, username/password login API is disabled by Evernote.
