### ISSUE TITLE
[Bug]: Stacktrace on init

### ISSUE THREAD

**Issue by sionsmith** [vzhd1701/evernote-backup#105]
### evernote-backup version

version 1.9.3

### What OS are you using?

MacOS

### OS Version / Linux distribution

14.5

### Bug description

Install works fine, when running `evernote-backup init-db` I get the following stacktrace.

### Log excerpt

```shell
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/evernote_backup/cli.py", line 305, in main
    cli()
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/evernote_backup/cli.py", line 158, in init_db
    cli_app.init_db(
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/evernote_backup/cli_app.py", line 38, in init_db
    auth_token = get_auth_token(
                 ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/evernote_backup/cli_app_auth.py", line 56, in get_auth_token
    return evernote_login_password(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/evernote_backup/cli_app_auth_password.py", line 56, in evernote_login_password
    auth_res = auth_client.login(auth_user, auth_password)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/evernote_backup/evernote_client_auth.py", line 27, in login
    return self.user_store.authenticateLongSessionV2(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/evernote_backup/evernote_client.py", line 138, in wrapper
    return target_method_retry(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/evernote_backup/evernote_client_util.py", line 28, in wrapper
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/evernote_backup/evernote_client_classes.py", line 294, in authenticateLongSessionV2
    return self.recv_authenticateLongSession()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/evernote-backup/1.9.3/libexec/lib/python3.12/site-packages/evernote/edam/userstore/UserStore.py", line 781, in recv_authenticateLongSession
    raise result.systemException
evernote.edam.error.ttypes.EDAMSystemException: EDAMSystemException(message=None, errorCode=8, rateLimitDuration=None)
```

**Comment by llity** [comment]
Having the same problem

**Comment by triuzzi** [comment]
Hello, @sionsmith and @llity, use `evernote-backup init-db --oauth` instead.

**Comment by Houska1** [comment]
I'm not the developer, but I've proposed an edit to the README documentation to clarify the situation as a stopgap. See https://github.com/vzhd1701/evernote-backup/pull/109

**Comment by glerner** [comment]
in Linux Mint 21.2

`pipx install evernote-backup`
Command 'pipx' not found, but can be installed with:
`sudo apt install pipx`

`pipx install evernote-backup`

`evernote-backup init-db`
gives long list of function calls, ending in: 

```
  File "/home/USER/.local/pipx/venvs/evernote-backup/lib/python3.10/site-packages/evernote_backup/evernote_client_classes.py", line 294, in authenticateLongSessionV2
    return self.recv_authenticateLongSession()
  File "/home/USER/.local/pipx/venvs/evernote-backup/lib/python3.10/site-packages/evernote/edam/userstore/UserStore.py", line 772, in recv_authenticateLongSession
    raise x
thrift.Thrift.TApplicationException: <unprintable TApplicationException object>

```
The suggestion 
`evernote-backup init-db --oauth`
 instead, works.

**Comment by vzhd1701** [comment]
Fixed in the new version. OAuth will be used by default now, username/password login API is disabled by Evernote.
