### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by robdejonge** [vzhd1701/evernote-backup#11]
Output: 
```
% ~/.local/bin/evernote-backup export /srv/Data-Backup/Rob/Evernote
Reading database en_backup.db...
Exporting notes...
  [##############################------]  42/49  00:01:33  Paper Records         
Traceback (most recent call last):
  File "/home/rob/.local/lib/python3.9/site-packages/evernote_backup/cli.py", line 272, in main
    cli()
  File "/home/rob/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/rob/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/rob/.local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rob/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rob/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/rob/.local/lib/python3.9/site-packages/evernote_backup/cli.py", line 233, in export
    cli_app.export(
  File "/home/rob/.local/lib/python3.9/site-packages/evernote_backup/cli_app.py", line 146, in export
    exporter.export_notebooks(single_notes, include_trash)
  File "/home/rob/.local/lib/python3.9/site-packages/evernote_backup/note_exporter.py", line 52, in export_notebooks
    self._export_active(single_notes)
  File "/home/rob/.local/lib/python3.9/site-packages/evernote_backup/note_exporter.py", line 77, in _export_active
    self._export_notes(nb, single_notes)
  File "/home/rob/.local/lib/python3.9/site-packages/evernote_backup/note_exporter.py", line 88, in _export_notes
    self._output_notebook(parent_dir, notebook.name, notes_source)
  File "/home/rob/.local/lib/python3.9/site-packages/evernote_backup/note_exporter.py", line 116, in _output_notebook
    _write_export_file(notebook_path, notes_source)
  File "/home/rob/.local/lib/python3.9/site-packages/evernote_backup/note_exporter.py", line 137, in _write_export_file
    for note in note_source:  # noqa: WPS440
  File "/home/rob/.local/lib/python3.9/site-packages/evernote_backup/note_storage.py", line 287, in iter_notes
    cur = con.execute(
MemoryError
```
The notebook being exported is particularly large. It contains about 2000 notes, each with small PDF files in them. I was running this on a 4GB Raspberry Pi. It clearly ran out of memory. 

What I don't understand is why adding an 8GB swap file did not make any difference. 

Any guidance on how I can resolve this challenge? Your script performs really well and I'd like to use it for daily backups of my Evernote account.

**Comment by vzhd1701** [comment]
The problem was in the wrong SQL index. Because of it, SQLite tried to create temporary table, which is most likely caused the memory leak.

Should be fixed now, please try exporting again using new version.

**Comment by robdejonge** [comment]
Fantastic! It's working a charm, even with the swap completely disabled. 
Thanks very much for fixing this so quickly, sincerely appreciated.
