### ISSUE TITLE
[Bug]: login error

### ISSUE THREAD

**Issue by nUser0** [vzhd1701/evernote-backup#113]
### evernote-backup version

1.9.3

### What OS are you using?

Windows

### OS Version / Linux distribution

windows 11

### Bug description

(base) C:\Users\Lenovo>evernote-backup init-db --backend china
Logging in to Evernote...
Username or Email: xxx@xxx.xxx
Password:
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\evernote_backup\cli.py", line 305, in main
    cli()
  File "D:\anaconda3\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\anaconda3\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\anaconda3\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\anaconda3\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\anaconda3\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\anaconda3\lib\site-packages\evernote_backup\cli.py", line 158, in init_db
    cli_app.init_db(
  File "D:\anaconda3\lib\site-packages\evernote_backup\cli_app.py", line 38, in init_db
    auth_token = get_auth_token(
  File "D:\anaconda3\lib\site-packages\evernote_backup\cli_app_auth.py", line 56, in get_auth_token
    return evernote_login_password(
  File "D:\anaconda3\lib\site-packages\evernote_backup\cli_app_auth_password.py", line 56, in evernote_login_password
    auth_res = auth_client.login(auth_user, auth_password)
  File "D:\anaconda3\lib\site-packages\evernote_backup\evernote_client_auth.py", line 27, in login
    return self.user_store.authenticateLongSessionV2(
  File "D:\anaconda3\lib\site-packages\evernote_backup\evernote_client.py", line 138, in wrapper
    return target_method_retry(*args, **kwargs)
  File "D:\anaconda3\lib\site-packages\evernote_backup\evernote_client_util.py", line 28, in wrapper
    return fun(*args, **kwargs)
  File "D:\anaconda3\lib\site-packages\evernote_backup\evernote_client_classes.py", line 294, in authenticateLongSessionV2
    return self.recv_authenticateLongSession()
  File "D:\anaconda3\lib\site-packages\evernote\edam\userstore\UserStore.py", line 779, in recv_authenticateLongSession
    raise result.userException
evernote.edam.error.ttypes.EDAMUserException: EDAMUserException(errorCode=8, parameter='consumerKey')

**Comment by DaleAndriy** [comment]
same error , fuck yingxiang

**Comment by HardToGiveaName** [comment]
same error...

**Comment by lumping** [comment]
Hey, guys, I had the same problem and I have solved it so far. Here's my solution, which I hope you'll find useful.
1.  Go to the website, and create your developer token.
 https://app.yinxiang.com/api/DeveloperToken.action
2.  Next add the token in your command 
evernote-backup init-db --backend china -t **your-token**

**Comment by nUser0** [comment]
Thank you. I'll try it later.



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/09/2024 18:35 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [vzhd1701/evernote-backup] [Bug]: login error (Issue #113) |

Hey, guys, I had the same problem and I have solved it so far. Here's my solution, which I hope you'll find useful.

Go to the website, and create your developer token.
https://app.yinxiang.com/api/DeveloperToken.action
Next add the token in your command
evernote-backup init-db --backend china -t your-token

**Comment by liaomars** [comment]
@lumping It's ok,Thanks

**Comment by Deali-Axy** [comment]
> Hey, guys, I had the same problem and I have solved it so far. Here's my solution, which I hope you'll find useful.
> 
> 1. Go to the website, and create your developer token.
>    https://app.yinxiang.com/api/DeveloperToken.action
> 2. Next add the token in your command
>    evernote-backup init-db --backend china **-t  your-token**

thanks! It worked!

**Comment by nUser0** [comment]
Thank you  very much.



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/22/2025 09:56 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [vzhd1701/evernote-backup] [Bug]: login error (Issue #113) |

Hey, guys, I had the same problem and I have solved it so far. Here's my solution, which I hope you'll find useful.

Go to the website, and create your developer token.
https://app.yinxiang.com/api/DeveloperToken.action
Next add the token in your command
evernote-backup init-db --backend china -t your-token

thanks! It worked!

**Comment by silentzone** [comment]
> Hey, guys, I had the same problem and I have solved it so far. Here's my solution, which I hope you'll find useful.
> 
> 1. Go to the website, and create your developer token.
>    https://app.yinxiang.com/api/DeveloperToken.action
> 2. Next add the token in your command
>    evernote-backup init-db --backend china **-t  your-token**

thx, that`s a lot of help

**Comment by tinyvane** [comment]
Thanks, that helps a lot.

**Comment by vzhd1701** [comment]
Yinxiang API token is updated in the new version.
