### ISSUE TITLE
[Bug]: Logging Account ssl.SSLCertVerificationError

### ISSUE THREAD

**Issue by phh95** [vzhd1701/evernote-backup#20]
### evernote-backup version

evernote-backup 1.9.0

### What OS are you using?

MacOS

### OS Version / Linux distribution

MacOS 12.1

### Bug description

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/29042617/181905461-5c77fe9d-4275-474f-95f5-5a66ca8fe810.png">

Hi, I try to use your tools to export my notes from yinxiang，when I first try to log in my account, it run error with `ssl.SSLCertVerificationError`，how can I deal with it? 

Please help me, thank you.

### Log excerpt

```shell
Traceback (most recent call last):
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/evernote_backup/cli.py", line 305, in main
    cli()
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/evernote_backup/cli.py", line 158, in init_db
    cli_app.init_db(
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/evernote_backup/cli_app.py", line 38, in init_db
    auth_token = get_auth_token(
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/evernote_backup/cli_app_auth.py", line 56, in get_auth_token
    return evernote_login_password(
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/evernote_backup/cli_app_auth_password.py", line 56, in evernote_login_password
    auth_res = auth_client.login(auth_user, auth_password)
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/evernote_backup/evernote_client_auth.py", line 27, in login
    return self.user_store.authenticateLongSessionV2(
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/evernote_backup/evernote_client.py", line 138, in wrapper
    return target_method_retry(*args, **kwargs)
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/evernote_backup/evernote_client_util.py", line 28, in wrapper
    return fun(*args, **kwargs)
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/evernote_backup/evernote_client_classes.py", line 283, in authenticateLongSessionV2
    self.send_authenticateLongSessionV2(
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/evernote_backup/evernote_client_classes.py", line 328, in send_authenticateLongSessionV2
    self._oprot.trans.flush()
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/thrift/transport/THttpClient.py", line 113, in _f
    result = f(*args, **kwargs)
  File "/Users/penghonghao/.local/pipx/venvs/evernote-backup/lib/python3.9/site-packages/thrift/transport/THttpClient.py", line 146, in flush
    self.__http.endheaders()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1422, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
```

**Comment by vzhd1701** [comment]
Do you have Python installed as a separate package?
Try running `/Applications/Python\ 3.9/Install\ Certificates.command`

**Comment by phh95** [comment]
Thank you. I'm not sure whether python in my mac is a separate package, but I make it by run `ln -s /etc/ssl/* /Library/Frameworks/Python.framework/Versions/3.9/etc/openssl`

the solution is found in stackoverflow   https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

Your project help me a lot, because Evernote in China named Yinxiang is getting worse and worse, the newest version stop us from exporting enex format instead of a new format——notes, this is a serect format. I think Yinxiang is trying to trap users.

**Comment by vzhd1701** [comment]
I am glad to hear that you find my tool useful! :)

AFAIK their new export format is still enex, but they encrypt note content now. Seems like it's the client that is doing the encryption since `evernote-backup` is still able to download plain text notes from the server. I haven't investigated it deep though. It may just be some static key that can be extracted from their client. They used to encrypt account token in the old Evernote version using [static key + disk serial number](https://github.com/vzhd1701/evertoken/blob/eda03e670b77db835b74a0b846c484713ca8aed7/evernote_exb.go#L189).
