### ISSUE TITLE
[Bug]: Crashes on Evernote Outage/Maintenance

### ISSUE THREAD

**Issue by dgreen** [vzhd1701/evernote-backup#29]
### evernote-backup version

1.9.2

### What OS are you using?

MacOS

### OS Version / Linux distribution

ARM64, M1

### Bug description

Crashes on attempt to do `evernote-backup sync` which has been working quite well through yesterday.

Guessed that it might be reauth time so I tried `evernote-backup reauth` which also failed after collecting email and password (but not the 2FA).

### Log excerpt

```shell
√ evernoteBackup % evernote-backup reauth
Reading database en_backup.db...
Logging in to Evernote...
Username or Email: myemail@gmail.com
Password: 
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/cli.py", line 305, in main
    cli()
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/cli.py", line 291, in reauth
    cli_app.reauth(
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/cli_app.py", line 80, in reauth
    auth_token = get_auth_token(
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/cli_app_auth.py", line 56, in get_auth_token
    return evernote_login_password(
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/cli_app_auth_password.py", line 56, in evernote_login_password
    auth_res = auth_client.login(auth_user, auth_password)
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/evernote_client_auth.py", line 27, in login
    return self.user_store.authenticateLongSessionV2(
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/evernote_client.py", line 138, in wrapper
    return target_method_retry(*args, **kwargs)
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/evernote_client_util.py", line 28, in wrapper
    return fun(*args, **kwargs)
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/evernote_client_classes.py", line 294, in authenticateLongSessionV2
    return self.recv_authenticateLongSession()
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote/edam/userstore/UserStore.py", line 767, in recv_authenticateLongSession
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/thrift/protocol/TBinaryProtocol.py", line 145, in readMessageBegin
    type = self.readByte()
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/thrift/protocol/TBinaryProtocol.py", line 201, in readByte
    val, = unpack('!b', buff)
struct.error: unpack requires a buffer of 1 bytes

?1 evernoteBackup % evernote-backup --verbose reauth
Reading database en_backup.db...
Logging in to Evernote...
Username or Email: myemail@gmail.com
Password: 
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/cli.py", line 305, in main
    cli()
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/cli.py", line 291, in reauth
    cli_app.reauth(
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/cli_app.py", line 80, in reauth
    auth_token = get_auth_token(
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/cli_app_auth.py", line 56, in get_auth_token
    return evernote_login_password(
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/cli_app_auth_password.py", line 56, in evernote_login_password
    auth_res = auth_client.login(auth_user, auth_password)
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/evernote_client_auth.py", line 27, in login
    return self.user_store.authenticateLongSessionV2(
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/evernote_client.py", line 138, in wrapper
    return target_method_retry(*args, **kwargs)
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/evernote_client_util.py", line 28, in wrapper
    return fun(*args, **kwargs)
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote_backup/evernote_client_classes.py", line 294, in authenticateLongSessionV2
    return self.recv_authenticateLongSession()
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/evernote/edam/userstore/UserStore.py", line 767, in recv_authenticateLongSession
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/thrift/protocol/TBinaryProtocol.py", line 145, in readMessageBegin
    type = self.readByte()
  File "/opt/homebrew/Cellar/evernote-backup/1.9.2/libexec/lib/python3.10/site-packages/thrift/protocol/TBinaryProtocol.py", line 201, in readByte
    val, = unpack('!b', buff)
struct.error: unpack requires a buffer of 1 bytes
```

**Comment by dgreen** [comment]
Looks like it may be an Evernote server outage.  In which case, the minor bug is that an outage is not handled well.

**Comment by dgreen** [comment]
From: https://status.evernote.com

Scheduled maintenance beginning - 10/29/2022
Users may experience limited connectivity to our service for approximately the next 3 hours.

Feel free to close this issue if deemed not useful to fix.
