### ISSUE TITLE
[Bug]: Linux standalone binaries don't work

### ISSUE THREAD

**Issue by cgaspar** [vzhd1701/evernote-backup#32]
### evernote-backup version

1.9.2

### What OS are you using?

Linux

### OS Version / Linux distribution

Ubuntu 22.04.1 LTS

### Bug description

Can't run released binary:
```
$ ./evernote-backup -h
Traceback (most recent call last):
  File "evernote_backup/__main__.py", line 1, in <module>
  File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "evernote_backup/cli.py", line 11, in <module>
  File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "evernote_backup/cli_app.py", line 8, in <module>
  File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "evernote_backup/cli_app_storage.py", line 5, in <module>
  File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "evernote_backup/note_storage.py", line 4, in <module>
  File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "lzma.py", line 27, in <module>
ModuleNotFoundError: No module named '_lzma'
[807851] Failed to execute script __main__
```

**Comment by vzhd1701** [comment]
I've rebuilt standalone binaries. Please [re-download](https://github.com/vzhd1701/evernote-backup/releases/download/1.9.2/bin_evernote_backup_1.9.2_linux_x64.tar.gz) and tell how it works now.
