### ISSUE TITLE
Error: SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by patrickplaggenborg** [vzhd1701/evernote-backup#5]
Not sure what happens and why.

Getting this error when trying to login using `evernote-backup init-db`.

How can I help debug this?

```Logging in to Evernote...
Username or Email: *********
Password: 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/cli.py", line 272, in main
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/cli.py", line 147, in init_db
    cli_app.init_db(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/cli_app.py", line 36, in init_db
    auth_token = get_auth_token(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/cli_app_auth.py", line 52, in get_auth_token
    return evernote_login_password(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/cli_app_auth_password.py", line 56, in evernote_login_password
    auth_res = auth_client.login(auth_user, auth_password)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/evernote_client_auth.py", line 27, in login
    return self.user_store.authenticateLongSessionV2(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/evernote_client.py", line 138, in wrapper
    return target_method_retry(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/evernote_client_util.py", line 28, in wrapper
    return fun(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/evernote_client_classes.py", line 283, in authenticateLongSessionV2
    self.send_authenticateLongSessionV2(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/evernote_client_classes.py", line 328, in send_authenticateLongSessionV2
    self._oprot.trans.flush()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/thrift/transport/THttpClient.py", line 113, in _f
    result = f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/thrift/transport/THttpClient.py", line 146, in flush
    self.__http.endheaders()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
```

**Comment by vzhd1701** [comment]
Run this in terminal, that should fix it
```shell
$ open /Applications/Python\ 3.9/Install\ Certificates.command
```

**Comment by patrickplaggenborg** [comment]
That worked, thanks a lot!

**Comment by fifteenzhang** [comment]
with my SSLCertVerificationError。
 the solution is： for Yinxiang ，use command：  evernote-backup init-db --backend china
