### ISSUE TITLE
[Bug]: init-db gives " struct.error: unpack requires a buffer of 1 bytes"

### ISSUE THREAD

**Issue by p-phillips** [vzhd1701/evernote-backup#50]
### evernote-backup version

1.9.2

### What OS are you using?

Linux

### OS Version / Linux distribution

Ubuntu 20.04

### Bug description

I can no longer  initialise the database - I get this error:

```
evernote-backup init-db
Logging in to Evernote...
Username or Email: mynamehere
Password: 
Traceback (most recent call last):
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/evernote_backup/cli.py", line 305, in main
    cli()
........
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/thrift/protocol/TBinaryProtocol.py", line 201, in readByte
    val, = unpack('!b', buff)
struct.error: unpack requires a buffer of 1 bytes
```

I've tried re-installing and tried multiple times to init-db but now I keep getting this error.

Note that last night, the first time i tried it, it worked OK, and I was able to run a sync, but no longer.

Any help appreciated.
Pete
 

### Log excerpt

```shell
pete@star:~/src/evernote-backup/tmp/ > evernote-backup init-db
Logging in to Evernote...
Username or Email: mynamehere
Password: 
Traceback (most recent call last):
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/evernote_backup/cli.py", line 305, in main
    cli()
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/evernote_backup/cli.py", line 158, in init_db
    cli_app.init_db(
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/evernote_backup/cli_app.py", line 38, in init_db
    auth_token = get_auth_token(
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/evernote_backup/cli_app_auth.py", line 56, in get_auth_token
    return evernote_login_password(
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/evernote_backup/cli_app_auth_password.py", line 56, in evernote_login_password
    auth_res = auth_client.login(auth_user, auth_password)
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/evernote_backup/evernote_client_auth.py", line 27, in login
    return self.user_store.authenticateLongSessionV2(
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/evernote_backup/evernote_client.py", line 138, in wrapper
    return target_method_retry(*args, **kwargs)
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/evernote_backup/evernote_client_util.py", line 28, in wrapper
    return fun(*args, **kwargs)
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/evernote_backup/evernote_client_classes.py", line 294, in authenticateLongSessionV2
    return self.recv_authenticateLongSession()
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/evernote/edam/userstore/UserStore.py", line 767, in recv_authenticateLongSession
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/thrift/protocol/TBinaryProtocol.py", line 145, in readMessageBegin
    type = self.readByte()
  File "/home/pete/.local/pipx/venvs/evernote-backup/lib/python3.8/site-packages/thrift/protocol/TBinaryProtocol.py", line 201, in readByte
    val, = unpack('!b', buff)
struct.error: unpack requires a buffer of 1 bytes
```

**Comment by vanstr** [comment]
Same issue on MacOS with docker and brew install. Could be related to they update https://discussion.evernote.com/forums/topic/148113-2023-10-04-outage/

**Comment by p-phillips** [comment]
Yes - looks like this was  down to the problem they had with the Evernote site earlier today - it's now working.
