### ISSUE TITLE
[Bug]: sync raise result.notFoundException

### ISSUE THREAD

**Issue by bsszds** [vzhd1701/evernote-backup#63]
### evernote-backup version

1.9.3

### What OS are you using?

Windows

### OS Version / Linux distribution

win11 23H2 专业版

### Bug description

Run evernote-backup sync for the first time.
 File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote\edam\notestore\NoteStore.py", line 4174, in recv_getNote
    raise result.notFoundException
evernote.edam.error.ttypes.EDAMNotFoundException: EDAMNotFoundException(message=None, identifier='Note.guid', key='977af345-fcb6-40ad-9477-a92389469ca0')

but,
Run evernote-backup sync a second time.
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\thrift\protocol\TBinaryProtocol.py", line 201, in readByte
    val, = unpack('!b', buff)
struct.error: unpack requires a buffer of 1 bytes

### Log excerpt

one!!!

Reading database en_backup.db...
Authorizing auth token, china backend...
Successfully authenticated as *********!
Current login will expire at 2024-12-17 09:08:53.
Syncing user notebooks...
  [####################################]  191262/191262
Syncing linked notebooks...
2770 note(s) to download...
Requesting access to 2 linked notebook(s)...
Downloading 2770 note(s)...
  [#####################---------------]  1635/2770  00:16:11Exception caught while downloading note '参赛: 031- 蝴蝶V1 版'!
Aborting, please wait...

Traceback (most recent call last):
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\cli.py", line 305, in main
    cli()
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\cli.py", line 211, in sync
    cli_app.sync(
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\cli_app.py", line 128, in sync
    note_synchronizer.sync()
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\note_synchronizer.py", line 215, in sync
    self._download_scheduled_notes(notes_to_sync)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\note_synchronizer.py", line 359, in _download_scheduled_notes
    self._process_download_chunk(
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\note_synchronizer.py", line 387, in _process_download_chunk
    raise f_exc
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\note_synchronizer.py", line 136, in __call__
    note = self.download_note(note_id)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\note_synchronizer.py", line 148, in download_note
    return self._note_client.get_note(note_id)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\evernote_client_sync.py", line 39, in get_note
    note = self.note_store.getNote(
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\evernote_client.py", line 131, in wrapper
    return functools.partial(
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\evernote_client_util.py", line 28, in wrapper
    return fun(*args, **kwargs)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote\edam\notestore\NoteStore.py", line 4142, in getNote
    return self.recv_getNote()
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote\edam\notestore\NoteStore.py", line 4174, in recv_getNote
    raise result.notFoundException
evernote.edam.error.ttypes.EDAMNotFoundException: EDAMNotFoundException(message=None, identifier='Note.guid', key='977af345-fcb6-40ad-9477-a92389469ca0')

two!!!

Reading database en_backup.db...
Authorizing auth token, china backend...
Successfully authenticated as *********!
Current login will expire at 2024-12-17 09:08:53.
Syncing user notebooks...
User notebooks are up to date, nothing to sync!
Syncing linked notebooks...
Traceback (most recent call last):
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\cli.py", line 305, in main
    cli()
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\cli.py", line 211, in sync
    cli_app.sync(
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\cli_app.py", line 128, in sync
    note_synchronizer.sync()
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\note_synchronizer.py", line 207, in sync
    self._sync_linked_notebook(l_notebook)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\note_synchronizer.py", line 286, in _sync_linked_notebook
    for chunk in l_notebook_chunks:
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\evernote_client_sync.py", line 83, in iter_linked_notebook_sync_chunks
    chunk = ln_note_store.getLinkedNotebookSyncChunk(
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\evernote_client.py", line 131, in wrapper
    return functools.partial(
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote_backup\evernote_client_util.py", line 28, in wrapper
    return fun(*args, **kwargs)
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote\edam\notestore\NoteStore.py", line 2759, in getLinkedNotebookSyncChunk
    return self.recv_getLinkedNotebookSyncChunk()
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\evernote\edam\notestore\NoteStore.py", line 2774, in recv_getLinkedNotebookSyncChunk
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\thrift\protocol\TBinaryProtocol.py", line 145, in readMessageBegin
    type = self.readByte()
  File "c:\users\bsszds\appdata\local\programs\python\python38\lib\site-packages\thrift\protocol\TBinaryProtocol.py", line 201, in readByte
    val, = unpack('!b', buff)
struct.error: unpack requires a buffer of 1 bytes

**Comment by bsszds** [comment]
参考这个思路，evernote-backup reauth，重新搜集账户信息
https://github.com/vzhd1701/evernote-backup/issues/29

又开始重新下载了
![image](https://github.com/vzhd1701/evernote-backup/assets/52306372/2ce6dd59-3d70-4c49-bdf7-5085c2fef61e)
