### ISSUE TITLE
Exception caught when downloading note

### ISSUE THREAD

**Issue by patrickplaggenborg** [vzhd1701/evernote-backup#7]
While performing the initial sync I bumped into this error `Exception caught while downloading note`.

It was toward the end, when there were 29 notes left to sync, out of 9049 notes in total.

Thankfully, running the sync command for the second time it successfully synced the remaining 29 notes.
Running the sync for the third time successfully said `Synchronization completed!`

Not sure if I can help you debug this because I can't reproduce it, but this log might be helpful.

```python
 Exception caught while downloading note 'xxxxx'!
Aborting, please wait...

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/cli.py", line 272, in main
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/cli.py", line 199, in sync
    cli_app.sync(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/cli_app.py", line 123, in sync
    note_synchronizer.sync()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/note_synchronizer.py", line 215, in sync
    self._download_scheduled_notes(notes_to_sync)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/note_synchronizer.py", line 360, in _download_scheduled_notes
    self._process_download_chunk(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/note_synchronizer.py", line 388, in _process_download_chunk
    raise f_exc
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/note_synchronizer.py", line 136, in __call__
    note = self.download_note(note_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/note_synchronizer.py", line 148, in download_note
    return self._note_client.get_note(note_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/evernote_client_sync.py", line 39, in get_note
    note = self.note_store.getNote(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/evernote_client.py", line 131, in wrapper
    return functools.partial(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote_backup/evernote_client_util.py", line 28, in wrapper
    return fun(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote/edam/notestore/NoteStore.py", line 4142, in getNote
    return self.recv_getNote()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/evernote/edam/notestore/NoteStore.py", line 4170, in recv_getNote
    raise result.userException
evernote.edam.error.ttypes.EDAMUserException: EDAMUserException(errorCode=9, parameter='authenticationToken')
```

**Comment by vzhd1701** [comment]
Evernote server throws occasional errors from time to time, maybe due to overload. This one is strange, though, because it says that your authentication token is expired, which is nonsense since you successfully finished the sync with the same token.

`evernote-backup` processes notes atomically, which means server-side errors shouldn't affect sync database integrity. So it' resistant to this kind of glitches.

**Comment by patrickplaggenborg** [comment]
Thanks for explaining. Great to hear that the database integrity after this is still good.
