### ISSUE TITLE
[Bug]: evernote.edam.error.ttypes.EDAMUserException: EDAMUserException(errorCode=8, parameter='consumerKey')

### ISSUE THREAD

**Issue by stonewoodone** [vzhd1701/evernote-backup#85]
### evernote-backup version

1.9.3

### What OS are you using?

Windows

### OS Version / Linux distribution

windows 10

### Bug description

![image](https://github.com/vzhd1701/evernote-backup/assets/36728213/5dc65e69-7f23-4805-9073-42d3932cdae9)

**Comment by stonewoodone** [comment]
(base) (.venv) PS D:\1\pythonProject1\.venv\Lib>  evernote-backup init-db --backend china
Logging in to Evernote...
Username or Email: stonewood@sohu.com
Password: 
Traceback (most recent call last):
  File "D:\1\pythonProject1\.venv\lib\site-packages\evernote_backup\cli.py", line 305, in main
    cli()
  File "D:\1\pythonProject1\.venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\1\pythonProject1\.venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\1\pythonProject1\.venv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\1\pythonProject1\.venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\1\pythonProject1\.venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\1\pythonProject1\.venv\lib\site-packages\evernote_backup\cli.py", line 158, in init_db
    cli_app.init_db(
  File "D:\1\pythonProject1\.venv\lib\site-packages\evernote_backup\cli_app.py", line 38, in init_db
    auth_token = get_auth_token(
  File "D:\1\pythonProject1\.venv\lib\site-packages\evernote_backup\cli_app_auth.py", line 56, in get_auth_token
    return evernote_login_password(
  File "D:\1\pythonProject1\.venv\lib\site-packages\evernote_backup\cli_app_auth_password.py", line 56, in evernote_login_password
    auth_res = auth_client.login(auth_user, auth_password)
  File "D:\1\pythonProject1\.venv\lib\site-packages\evernote_backup\evernote_client_auth.py", line 27, in login
    return self.user_store.authenticateLongSessionV2(
  File "D:\1\pythonProject1\.venv\lib\site-packages\evernote_backup\evernote_client.py", line 138, in wrapper
    return target_method_retry(*args, **kwargs)
  File "D:\1\pythonProject1\.venv\lib\site-packages\evernote_backup\evernote_client_util.py", line 28, in wrapper
    return fun(*args, **kwargs)
  File "D:\1\pythonProject1\.venv\lib\site-packages\evernote_backup\evernote_client_classes.py", line 294, in authenticateLongSessionV2
    return self.recv_authenticateLongSession()
  File "D:\1\pythonProject1\.venv\lib\site-packages\evernote\edam\userstore\UserStore.py", line 779, in recv_authenticateLongSession
    raise result.userException
evernote.edam.error.ttypes.EDAMUserException: EDAMUserException(errorCode=8, parameter='consumerKey')
