### ISSUE TITLE
[Bug]: no module named pyutil

### ISSUE THREAD

**Issue by tfriedel** [vzhd1701/evernote-backup#89]
### evernote-backup version

1.9.3

### What OS are you using?

Linux

### OS Version / Linux distribution

Ubuntu 24.04

### Bug description

I installed evernote-backup with pipx, but there's a package missing on python 3.12.1:
ModuleNotFoundError: No module named 'pyutil'

### Log excerpt
I ran 
```shell

pipx install evernote-backup  
```
Then:
```
❯ evernote-backup init-db
Traceback (most recent call last):
  File "/home/thomas/.local/share/pipx/venvs/evernote-backup/lib/python3.12/site-packages/oauth2/_version.py", line 13, in <module>
    from pyutil.version_class import Version as pyutil_Version
ModuleNotFoundError: No module named 'pyutil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomas/.local/bin/evernote-backup", line 5, in <module>
    from evernote_backup.cli import main
  File "/home/thomas/.local/share/pipx/venvs/evernote-backup/lib/python3.12/site-packages/evernote_backup/cli.py", line 11, in <module>
    from evernote_backup import cli_app, config_defaults
  File "/home/thomas/.local/share/pipx/venvs/evernote-backup/lib/python3.12/site-packages/evernote_backup/cli_app.py", line 7, in <module>
    from evernote_backup.cli_app_auth import get_auth_token, get_sync_client
  File "/home/thomas/.local/share/pipx/venvs/evernote-backup/lib/python3.12/site-packages/evernote_backup/cli_app_auth.py", line 4, in <module>
    from evernote_backup.cli_app_auth_oauth import evernote_login_oauth
  File "/home/thomas/.local/share/pipx/venvs/evernote-backup/lib/python3.12/site-packages/evernote_backup/cli_app_auth_oauth.py", line 9, in <module>
    from evernote_backup.evernote_client_oauth import (
  File "/home/thomas/.local/share/pipx/venvs/evernote-backup/lib/python3.12/site-packages/evernote_backup/evernote_client_oauth.py", line 7, in <module>
    import oauth2
  File "/home/thomas/.local/share/pipx/venvs/evernote-backup/lib/python3.12/site-packages/oauth2/__init__.py", line 47, in <module>
    from ._version import __version__
  File "/home/thomas/.local/share/pipx/venvs/evernote-backup/lib/python3.12/site-packages/oauth2/_version.py", line 16, in <module>
    from distutils.version import LooseVersion as distutils_Version
ModuleNotFoundError: No module named 'distutils'
```

**Comment by wintersolutions** [comment]
Same error here after upgrading from Python 3.11.8 to 3.12.3 on Manjaro/Arch.

**Comment by vzhd1701** [comment]
oauth2 is no longer used
